# Generated by Django 3.2.4 on 2021-06-20 16:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MAINAPP', '0002_alter_userprofileinfo_phone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofileinfo',
            name='phone',
            field=models.CharField(blank=True, max_length=12),
        ),
    ]
