# Generated by Django 3.2.4 on 2021-06-24 05:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MAINAPP', '0004_usernotification'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usernotification',
            name='email',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='usernotification',
            name='name',
            field=models.CharField(max_length=200),
        ),
    ]
