# Generated by Django 3.2.4 on 2021-06-24 05:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MAINAPP', '0005_auto_20210624_1052'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usernotification',
            name='email',
            field=models.EmailField(max_length=128),
        ),
        migrations.AlterField(
            model_name='usernotification',
            name='name',
            field=models.CharField(max_length=128),
        ),
    ]
