# Generated by Django 3.2.4 on 2021-06-26 04:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('MAINAPP', '0009_useremail'),
    ]

    operations = [
        migrations.RenameField(
            model_name='useremail',
            old_name='attach',
            new_name='mail_image',
        ),
    ]
