# Generated by Django 3.2.4 on 2021-06-26 05:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('MAINAPP', '0011_useremail_mail_file'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='useremail',
            name='mail_file',
        ),
        migrations.RemoveField(
            model_name='useremail',
            name='mail_image',
        ),
    ]
