# Generated by Django 3.2.4 on 2021-06-26 07:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MAINAPP', '0012_auto_20210626_1119'),
    ]

    operations = [
        migrations.CreateModel(
            name='Recipe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(blank=True)),
                ('caption', models.TextField(blank=True)),
                ('ingredients', models.TextField(blank=True)),
                ('procedure', models.TextField(blank=True)),
                ('conclusion_or_note', models.TextField(blank=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='')),
                ('featured', models.BooleanField(blank=True, default=False, null=True)),
            ],
        ),
    ]
