# Generated by Django 3.2.4 on 2021-06-26 09:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MAINAPP', '0015_auto_20210626_1332'),
    ]

    operations = [
        migrations.CreateModel(
            name='HealthTips',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=500)),
                ('caption', models.CharField(blank=True, max_length=2000)),
                ('introduction', models.TextField(blank=True)),
                ('description', models.TextField(blank=True)),
                ('conclusion', models.TextField(blank=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='')),
                ('add_to_home', models.BooleanField(blank=True, default=False, null=True)),
            ],
        ),
        migrations.RenameField(
            model_name='recipe',
            old_name='featured',
            new_name='add_to_home',
        ),
        migrations.AlterField(
            model_name='recipe',
            name='name',
            field=models.CharField(blank=True, max_length=500),
        ),
    ]
