# Generated by Django 3.2.4 on 2021-06-26 09:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('MAINAPP', '0016_auto_20210626_1447'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='HealthTips',
            new_name='HealthTip',
        ),
    ]
