# Generated by Django 3.2.4 on 2021-06-26 09:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('MAINAPP', '0017_rename_healthtips_healthtip'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='healthtip',
            name='conclusion',
        ),
        migrations.RemoveField(
            model_name='healthtip',
            name='description',
        ),
        migrations.RemoveField(
            model_name='healthtip',
            name='introduction',
        ),
    ]
