# Generated by Django 3.2.4 on 2021-06-26 10:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MAINAPP', '0018_auto_20210626_1527'),
    ]

    operations = [
        migrations.AddField(
            model_name='healthtip',
            name='conclusion',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='healthtip',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='healthtip',
            name='introduction',
            field=models.TextField(blank=True),
        ),
    ]
