# Generated by Django 3.2.4 on 2021-06-26 10:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MAINAPP', '0019_auto_20210626_1533'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='healthtip',
            name='image',
        ),
        migrations.AddField(
            model_name='healthtip',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to=''),
        ),
    ]
