# Generated by Django 3.2.4 on 2021-06-26 10:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MAINAPP', '0020_auto_20210626_1542'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='healthtip',
            name='file',
        ),
        migrations.AddField(
            model_name='healthtip',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
