# Generated by Django 3.2.4 on 2021-06-27 12:55

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('MAINAPP', '0022_auto_20210626_2143'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Recipe',
        ),
        migrations.AddField(
            model_name='healthblog',
            name='posted_by',
            field=models.CharField(blank=True, help_text='Add author name', max_length=200),
        ),
        migrations.AddField(
            model_name='healthblog',
            name='posted_on',
            field=models.DateField(blank=True, default=django.utils.timezone.now, help_text='Add date '),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='healthblog',
            name='caption',
            field=models.CharField(blank=True, help_text='Please add min 45 and max 55 (count space as well)characters to adjust it in flip card size', max_length=200),
        ),
        migrations.AlterField(
            model_name='healthblog',
            name='name',
            field=models.CharField(blank=True, help_text='Please add max 25 characters(count space as well) to adjust it in flip card size', max_length=200),
        ),
    ]
