# Generated by Django 3.2.4 on 2021-06-27 13:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MAINAPP', '0024_alter_healthblog_caption'),
    ]

    operations = [
        migrations.AlterField(
            model_name='healthblog',
            name='posted_by',
            field=models.CharField(blank=True, default='Foram Shah', help_text='Add author name', max_length=200),
        ),
    ]
