# Generated by Django 3.2.4 on 2021-06-28 04:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MAINAPP', '0025_alter_healthblog_posted_by'),
    ]

    operations = [
        migrations.CreateModel(
            name='AutomatedEmail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=300)),
                ('subject', models.TextField(blank=True)),
                ('body', models.TextField(blank=True)),
            ],
        ),
        migrations.RenameModel(
            old_name='UserNotification',
            new_name='Subscriber',
        ),
        migrations.DeleteModel(
            name='UserEmail',
        ),
        migrations.AlterField(
            model_name='healthblog',
            name='posted_by',
            field=models.CharField(blank=True, help_text='Add author name', max_length=200),
        ),
    ]
