# Generated by Django 3.2.4 on 2021-06-30 11:01

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('MAINAPP', '0026_auto_20210628_0941'),
    ]

    operations = [
        migrations.CreateModel(
            name='statistic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=300)),
                ('count', models.IntegerField()),
                ('label', models.CharField(blank=True, max_length=300)),
            ],
        ),
        migrations.AlterField(
            model_name='healthblog',
            name='caption',
            field=models.CharField(blank=True, help_text='Please add max 55  to 60 characters (count space as well)', max_length=500),
        ),
        migrations.AlterField(
            model_name='healthblog',
            name='name',
            field=models.CharField(blank=True, help_text='Please add max 20 to 30 characters(count space as well) ', max_length=200),
        ),
        migrations.AlterField(
            model_name='healthblog',
            name='posted_on',
            field=models.DateField(blank=True, default=django.utils.timezone.now, help_text='mandatory field'),
        ),
    ]
