# Generated by Django 3.2.4 on 2021-07-01 11:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('MAINAPP', '0031_auto_20210630_2132'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userfeedback',
            old_name='email',
            new_name='reviewer_email',
        ),
        migrations.RenameField(
            model_name='userfeedback',
            old_name='message',
            new_name='reviewer_message',
        ),
        migrations.RenameField(
            model_name='userfeedback',
            old_name='name',
            new_name='reviewer_name',
        ),
    ]
