# Generated by Django 3.2.4 on 2021-07-06 12:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MAINAPP', '0032_auto_20210701_1652'),
    ]

    operations = [
        migrations.CreateModel(
            name='Program',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('plan_name', models.CharField(blank=True, max_length=300)),
                ('about_plan', models.TextField(blank=True, help_text='Keep it short')),
                ('plan_introduction', models.TextField(blank=True)),
                ('plan_description_A', models.TextField(blank=True, help_text='What our plans include')),
                ('plan_description_B', models.TextField(blank=True, help_text='How our plan works')),
                ('plan_conclusion', models.TextField(blank=True)),
                ('plan_image', models.ImageField(blank=True, help_text='crop image as square before upload to adjust in the template', null=True, upload_to='')),
                ('add_plan_to_home', models.BooleanField(blank=True, default=False, help_text='Yes will enable to display it on home page', null=True)),
            ],
        ),
        migrations.AlterField(
            model_name='healthblog',
            name='name',
            field=models.CharField(blank=True, help_text='Please add max 20 to 30 characters(count space as well)', max_length=200),
        ),
    ]
