# Generated by Django 3.2.4 on 2021-07-09 18:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MAINAPP', '0033_auto_20210706_1816'),
    ]

    operations = [
        migrations.AlterField(
            model_name='healthblog',
            name='add_to_home',
            field=models.BooleanField(blank=True, default=False, help_text='Yes will enable to display it on home page (display max 6 posts in home page)', null=True),
        ),
        migrations.AlterField(
            model_name='healthblog',
            name='caption',
            field=models.CharField(blank=True, help_text='Keep caption short(max 2 lines)', max_length=500),
        ),
        migrations.AlterField(
            model_name='healthblog',
            name='image',
            field=models.ImageField(blank=True, help_text='crop image as square before upload to get uniform size in the page', null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='healthblog',
            name='name',
            field=models.CharField(blank=True, help_text='Keep name short(max 4 to 5 words)', max_length=200),
        ),
        migrations.AlterField(
            model_name='program',
            name='add_plan_to_home',
            field=models.BooleanField(blank=True, default=False, help_text='Yes will enable to display it on home page (display max 3 plans in home page)', null=True),
        ),
        migrations.AlterField(
            model_name='program',
            name='plan_conclusion',
            field=models.TextField(blank=True, help_text='You can also use it as end note , it appears in bold (not a mandatory field)'),
        ),
        migrations.AlterField(
            model_name='program',
            name='plan_description_A',
            field=models.TextField(blank=True, help_text='What our plans include (mandatory field)'),
        ),
        migrations.AlterField(
            model_name='program',
            name='plan_description_B',
            field=models.TextField(blank=True, help_text='How our plan works (mandatory field)'),
        ),
        migrations.AlterField(
            model_name='program',
            name='plan_image',
            field=models.ImageField(blank=True, help_text='crop image as square before upload to get uniform size in the page', null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='program',
            name='plan_introduction',
            field=models.TextField(blank=True, help_text='mandatory field'),
        ),
        migrations.AlterField(
            model_name='userfeedback',
            name='reviewer_message',
            field=models.TextField(blank=True, max_length=2000),
        ),
    ]
