# Generated by Django 3.2.4 on 2021-07-14 11:29

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('MAINAPP', '0034_auto_20210709_2358'),
    ]

    operations = [
        migrations.CreateModel(
            name='Workshop',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('shop_name', models.CharField(max_length=128)),
                ('enrolled', models.ManyToManyField(to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
