# Generated by Django 3.2.4 on 2021-07-14 13:30

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('MAINAPP', '0035_workshop'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='workshop',
            name='enrolled',
        ),
        migrations.RemoveField(
            model_name='workshop',
            name='shop_name',
        ),
        migrations.AddField(
            model_name='workshop',
            name='workshop_name',
            field=models.CharField(default='abc', max_length=300),
        ),
        migrations.AlterField(
            model_name='userprofileinfo',
            name='name',
            field=models.CharField(max_length=200),
        ),
        migrations.CreateModel(
            name='Workshop_Enrollment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('participant_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('workshop_enrolled', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='MAINAPP.workshop')),
            ],
        ),
        migrations.AddField(
            model_name='workshop',
            name='participants',
            field=models.ManyToManyField(through='MAINAPP.Workshop_Enrollment', to=settings.AUTH_USER_MODEL),
        ),
    ]
