# Generated by Django 3.2.4 on 2021-07-15 17:55

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('MAINAPP', '0037_auto_20210714_1933'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.CharField(max_length=300)),
                ('product_caption', models.TextField(blank=True, help_text='Keep short , one to two lines')),
                ('product_colors_available', models.CharField(max_length=400)),
                ('product_introduction', models.TextField(blank=True)),
                ('product_sub_heading', models.CharField(help_text='If you have a detailed description of product with sub heading add here', max_length=300)),
                ('product_sub_body', models.TextField(blank=True, help_text='Describe product  if have a detailed description')),
                ('product_conclusion', models.TextField(blank=True, help_text='You can use the conclusion as end note or any important message at the end')),
                ('product_image', models.ImageField(blank=True, help_text='crop image as square before upload to get uniform size in the page', null=True, upload_to='')),
            ],
        ),
        migrations.RemoveField(
            model_name='workshop_enrollment',
            name='workshop_enrolled',
        ),
        migrations.AddField(
            model_name='workshop',
            name='enable_enrollment',
            field=models.BooleanField(blank=True, default=True, help_text='Yes will enable enrollment ,No will disable enrollment', null=True),
        ),
        migrations.AddField(
            model_name='workshop',
            name='enable_home',
            field=models.BooleanField(blank=True, default=False, help_text='Yes will enable to display it on home page', null=True),
        ),
        migrations.AddField(
            model_name='workshop',
            name='sub_body1',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='workshop',
            name='sub_body2',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='workshop',
            name='sub_body3',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='workshop',
            name='sub_heading1',
            field=models.CharField(blank=True, max_length=300),
        ),
        migrations.AddField(
            model_name='workshop',
            name='sub_heading2',
            field=models.CharField(blank=True, max_length=300),
        ),
        migrations.AddField(
            model_name='workshop',
            name='sub_heading3',
            field=models.CharField(blank=True, max_length=300),
        ),
        migrations.AddField(
            model_name='workshop',
            name='workshop_caption',
            field=models.TextField(blank=True, help_text='Keep short , one to two lines'),
        ),
        migrations.AddField(
            model_name='workshop',
            name='workshop_duration',
            field=models.CharField(blank=True, help_text='workshop duration in days', max_length=300),
        ),
        migrations.AddField(
            model_name='workshop',
            name='workshop_introduction',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='workshop_enrollment',
            name='enrolled_on',
            field=models.DateField(blank=True, default=django.utils.timezone.now, help_text='mandatory field'),
        ),
        migrations.AddField(
            model_name='workshop_enrollment',
            name='participant_phone',
            field=models.CharField(blank=True, max_length=12),
        ),
    ]
