# Generated by Django 3.2.4 on 2021-07-20 04:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MAINAPP', '0040_auto_20210716_2132'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='product_price',
            field=models.CharField(blank=True, max_length=400),
        ),
    ]
